[taux_incidence]
dataset = ""
res_id_fra = "taux_fra.csv"
res_id_reg = "taux_reg.csv"
res_id_dep = "taux_dep.csv"
trendType = "normal"
nom = "Taux d'incidence"
unite = "Nombre de cas par semaine pour 100 000 habitant"

[taux_positivite]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id_fra = "taux_fra.csv"
res_id_reg = "taux_reg.csv"
res_id_dep = "taux_dep.csv"
trendType = "normal"
nom = "Taux de positivité"
unite = "%"

[hospitalisations]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Hospitalisations"
unite = "personnes hospitalisées"

[hospitalisations_moyenne_quotidienne]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre moyen de nouvelles hospitalisations quotidiennes"
unite = "personnes hospitalisées"

[retour_a_domicile]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre de retours à domicile"
unite = "personnes"

[retour_a_domicile_moyenne_quotidienne]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre moyen de retours à domicile quotidiens"
unite = "personnes"

[soins_critiques]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Hospitalisations en soins critiques"
unite = "personnes en soins critiques"

[soins_critiques_moyenne_quotidienne]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre moyen de nouvelles entrées en soins critiques quotidiennes"
unite = "personnes en soins critiques"

[deces]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Décès hospitaliers"
unite = "décès hospitaliers"

[deces_moyenne_quotidienne]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre moyen de décès quotidiens"
unite = "décès hospitaliers"

[deces_total]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese_fra.csv"
trendType = "normal"
nom = "Nombre total de décès"
unite = "décès"

[vaccins_premiere_dose]
dataset = "donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1"
res_id = "vaccin.csv"
trendType = "abnormal"
nom = "Nombre de personnes ayant reçu au moins une première injection"
unite = "personnes ayant reçues au moins une dose de vaccin"

[vaccins_vaccines]
dataset = "donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1"
res_id = "vaccin.csv"
trendType = "abnormal"
nom = "Nombre de personnes vaccinées"
unite = "personnes vaccinées"

[vaccins_premiere_dose_moyenne_quotidienne]
dataset = "donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1"
res_id = "vaccin.csv"
trendType = "abnormal"
nom = "Nombre moyen quotidien de personnes ayant reçu au moins une première injection"
unite = "personnes ayant reçues au moins une dose de vaccin"

[cas_positifs]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre moyen de nouveaux cas confirmés quotidiens sur 7 jours (J-3)"
unite = "cas positifs"

[facteur_reproduction]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id_fra = "synthese_fra.csv"
res_id_reg = "synthese.csv"
res_id_dep = "synthese.csv"
trendType = "normal"
nom = "Facteur de reproduction du virus"
unite = "R"

[taux_occupation]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id_fra = "synthese_fra.csv"
res_id_reg = "synthese.csv"
res_id_dep = "synthese.csv"
trendType = "normal"
nom = "Tension hospitalière sur la capacité en réanimation"
unite = "%"