version: 2

jobs:
  fetch:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/project/
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: /tmp
      - add_ssh_keys:
          fingerprints:
            - "6c:76:7b:00:20:3e:ea:0c:e8:d4:32:32:3b:28:7e:a7"
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Fetch datasets and generate data
          command: |
            pwd
            ls
            . venv/bin/activate
            python main.py
            python plot_kpi.py

            git clone https://github.com/geoffreyaldebert/covidbackend.git
            ls
      - persist_to_workspace:
          root: .
          paths:
            - ./venv
workflows:
  version: 2
  commit:
    jobs:
      - fetch
  cron_fetch:
    triggers:
      - schedule:
          cron: "0 20 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - fetch